export const message = [
  {
    id: 1,
    status: "Today",
    month: "June",
    date: "09, 2021",
    inbox_chat: [
      {
        id: 1,
        name: "Fahmi",
        body: "Kamu bisa menjadi yang lebih baik",
        color: "#FCEED3",
        time: "12.00",
      },
      {
        id: 2,
        name: "Ali",
        body: "Kamu bisa menjadi yang lebih baik",
        color: "#EEDCFF",
        time: "12.05",
      },
      {
        id: 3,
        name: "Husni",
        body: "Kamu pasti bisa melakukan tantangan ini",
        color: "#D2F2EA",
        time: "12.07",
      },
      {
        id: 4,
        name: "Herman",
        body: "Semangat yukkk",
        color: "#FCEED3",
        time: "12.10",
      },
      {
        id: 5,
        name: "Bima",
        body: "Jangan lupa berdoa, semangatt fahmii",
        color: "#EEDCFF",
        time: "12.11",
      },
      {
        id: 6,
        name: "Rahmi",
        body: "Aku yakin kamu bisa kok, semangat ya",
        color: "#D2F2EA",
        time: "12.15",
      },
      {
        id: 7,
        name: "Fahmi",
        body: "Kamu bisa menjadi yang lebih baik",
        color: "#FCEED3",
        time: "12.17",
      },
      {
        id: 8,
        name: "Ali",
        body: "Kamu bisa menjadi yang lebih baik",
        color: "#EEDCFF",
        time: "12.18",
      },
      {
        id: 9,
        name: "Husni",
        body: "Kamu pasti bisa melakukan tantangan ini",
        color: "#D2F2EA",
        time: "12.19",
      },
      {
        id: 10,
        name: "Herman",
        body: "Semangat yukkk",
        color: "#FCEED3",
        time: "12.21",
      },
      {
        id: 11,
        name: "Bima",
        body: "Jangan lupa berdoa, semangatt fahmii",
        color: "#EEDCFF",
        time: "12.25",
      },
      {
        id: 12,
        name: "Rahmi",
        body: "Aku yakin kamu bisa kok, semangat ya",
        color: "#D2F2EA",
        time: "12.30",
      },
      {
        id: 13,
        name: "Rahmi",
        body: "Aku yakin kamu bisa kok, semangat ya",
        color: "#FCEED3",
        time: "12.30",
      },
      {
        id: 14,
        name: "Rahmi",
        body: "Aku yakin kamu bisa kok, semangat ya",
        color: "#EEDCFF",
        time: "12.30",
      },
      {
        id: 15,
        name: "Rahmi",
        body: "Aku yakin kamu bisa kok, semangat ya",
        color: "#D2F2EA",
        time: "12.30",
      },
      {
        id: 16,
        name: "Rahmi",
        body: "Aku yakin kamu bisa kok, semangat ya",
        color: "#FCEED3",
        time: "12.30",
      },
      {
        id: 17,
        name: "Rahmi",
        body: "Aku yakin kamu bisa kok, semangat ya",
        color: "#EEDCFF",
        time: "12.30",
      },
      {
        id: 18,
        name: "Rahmi",
        body: "Aku yakin kamu bisa kok, semangat ya",
        color: "#D2F2EA",
        time: "12.30",
      },
      {
        id: 19,
        name: "Rahmi",
        body: "Aku yakin kamu bisa kok, semangat ya",
        color: "#FCEED3",
        time: "12.30",
      },
      {
        id: 20,
        name: "Rahmi",
        body: "Aku yakin kamu bisa kok, semangat ya",
        color: "#EEDCFF",
        time: "12.30",
      },
    ],
  },
];
