export const message = [
  {
    id: 1,
    status: "Today",
    month: "June",
    date: "09, 2021",
    inbox_chat: [
      {
        id: 1,
        name: "Fahmi",
        body: "Kamu bisa menjadi yang lebih baik",
        color: "#E9F3FF",
        time: "12.00",
      },
      {
        id: 2,
        name: "Ali",
        body: "Kamu bisa menjadi yang lebih baik",
        color: "#FDCFA4",
        time: "12.05",
      },
      {
        id: 3,
        name: "Husni",
        body: "Kamu pasti bisa melakukan tantangan ini",
        color: "#F9E9C3",
        time: "12.07",
      },
      {
        id: 4,
        name: "Herman",
        body: "Semangat yukkk",
        color: "#AFEBDB",
        time: "12.10",
      },
      {
        id: 5,
        name: "Bima",
        body: "Jangan lupa berdoa, semangatt fahmii",
        color: "#CBF1C2",
        time: "12.11",
      },
      {
        id: 6,
        name: "Rahmi",
        body: "Aku yakin kamu bisa kok, semangat ya",
        color: "#F9E0FD",
        time: "12.15",
      },
      {
        id: 7,
        name: "Fahmi",
        body: "Kamu bisa menjadi yang lebih baik",
        color: "#E9F3FF",
        time: "12.17",
      },
      {
        id: 8,
        name: "Ali",
        body: "Kamu bisa menjadi yang lebih baik",
        color: "#FDCFA4",
        time: "12.18",
      },
      {
        id: 9,
        name: "Husni",
        body: "Kamu pasti bisa melakukan tantangan ini",
        color: "#F9E9C3",
        time: "12.19",
      },
      {
        id: 10,
        name: "Herman",
        body: "Semangat yukkk",
        color: "#AFEBDB",
        time: "12.21",
      },
      {
        id: 11,
        name: "Bima",
        body: "Jangan lupa berdoa, semangatt fahmii",
        color: "#CBF1C2",
        time: "12.25",
      },
      {
        id: 12,
        name: "Rahmi",
        body: "Aku yakin kamu bisa kok, semangat ya",
        color: "#F9E0FD",
        time: "12.30",
      },
    ],
  },
  {
    id: 2,
    status: "New Message",
    month: null,
    date: null,
    inbox_chat: [
      {
        id: 1,
        name: "Ali",
        body: "Btw, kamu nanti jadi beli makan?",
        color: "#E9F3FF",
        time: "12.31",
      },
    ],
  },
];
